In [1]:
# Import Libraries With APIs

import tensorflow as tf
import keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passi

ImportError: cannot import name 'export_saved_model' from 'tensorflow.python.keras.saving.saved_model' (/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/__init__.py)

In [4]:
train_sentences = [
    'It will rain',
    'The weather is cloudy!',
    'Will it be raining today?',
    'It is a super hot day!'
]

In [6]:
 ### Train the Tokenizer
# Set up the tokenizer
tokenizer = Tokenizer(num_words = 100, oov_token = '<oov>')

#Train the tokenizer on training sentence
tokenizer.fit_on_texts(train_sentences)

#Store word index for the words in the sentence
word_index = tokenizer.word_index

In [8]:
## Create Sequences
sequences = tokenizer.texts_to_sequences(train_sentences)

In [10]:
## Pad Sequences
padded_seqs = pad_sequences(sequences)

print('Word Index--> ', word_index)
print('Train Sentences--> ', train_sentences)
print('Sequences--> ',sequences)
print('Padded Sequences-->', padded_seqs)

Word Index-->  {'it': 1, 'will': 2, 'is': 3, 'rain': 4, 'the': 5, 'weather': 6, 'cloudy': 7, 'be': 8, 'raining': 9, 'today': 10, 'a': 11, 'super': 12, 'hot': 13, 'day': 14, '<oov>': 15}
Train Sentences-->  ['It will rain', 'The weather is cloudy!', 'Will it be raining today?', 'It is a super hot day!']
Sequences-->  [[1, 2, 4], [5, 6, 3, 7], [2, 1, 8, 9, 10], [1, 3, 11, 12, 13, 14]]
Padded Sequences--> [[ 0  0  0  1  2  4]
 [ 0  0  5  6  3  7]
 [ 0  2  1  8  9 10]
 [ 1  3 11 12 13 14]]


In [12]:
### Customizing padded sequences with parameter
## Pad sequences with padding type, max_length and truncating parameter

padded_seqs = pad_sequences(sequences,
                           padding = "post",
                           maxlen = 5,
                           truncating = "post")
print(padded_seqs)

[[ 1  2  4  0  0]
 [ 5  6  3  7  0]
 [ 2  1  8  9 10]
 [ 1  3 11 12 13]]
